# Bu araç @keyiflerolsun tarafından | @KekikAkademi için yazılmıştır.

networks:
    local:
        driver: bridge

volumes:
    grafana:
    influxdb_data:
    influxdb_config:

services:
    keenetic_exporter:
        container_name : keenetic_exporter
        image          : keenetic_exporter:latest
        restart        : always
        build          : .
        network_mode   : host
        depends_on     :
            - grafana
            - influxdb

    grafana:
        container_name : grafana
        image          : grafana/grafana:latest
        restart        : always
        networks       :
            - local
        ports          :
            - 3000:3000
        volumes        :
            - grafana:/var/lib/grafana


    influxdb:
        container_name : influxdb
        image          : influxdb:latest
        restart        : always
        networks       :
            - local
        ports          :
            - 8086:8086
        volumes        :
            - influxdb_data:/var/lib/influxdb2
            - influxdb_config:/etc/influxdb2
        environment    :
            DOCKER_INFLUXDB_INIT_MODE        : setup
            DOCKER_INFLUXDB_INIT_ORG         : keenetic
            DOCKER_INFLUXDB_INIT_BUCKET      : keenetic
            DOCKER_INFLUXDB_INIT_RETENTION   : 52w
            DOCKER_INFLUXDB_INIT_ADMIN_TOKEN : DOCKER_CONFIG_TOKEN      # * openssl rand -hex 32
            DOCKER_INFLUXDB_INIT_USERNAME    : merhaba
            DOCKER_INFLUXDB_INIT_PASSWORD    : dunya12345
