# Bu araç @keyiflerolsun tarafından | @KekikAkademi için yazılmıştır.

version: "3.9"

networks:
    local:
        driver: bridge

volumes:
    influxdb:
    grafana:

services:
    keenetic_exporter:
        container_name : keenetic_exporter
        image          : keenetic_exporter:latest
        restart        : always
        build          : .
        network_mode   : host
        depends_on     :
            - grafana
            - influxdb

    grafana:
        container_name : grafana
        image          : grafana/grafana:latest
        restart        : always
        networks       :
            - local
        ports          :
            - 3000:3000
        volumes        :
            - grafana:/var/lib/grafana


    influxdb:
        container_name : influxdb
        image          : influxdb:1.8.1
        restart        : always
        networks       :
            - local
        ports          :
            - 8086:8086
        volumes        :
            - influxdb:/var/lib/influxdb
        environment    :
            INFLUXDB_DB                : keenetic
            INFLUXDB_HTTP_AUTH_ENABLED : true
            INFLUXDB_ADMIN_USER        : merhaba
            INFLUXDB_ADMIN_PASSWORD    : dunya