{
 "title": "pve.local",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "CPU Usage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - netdata_cpu_cpu_percentage_average{chart=\"cpu.cpu4\", cpu=\"cpu4\", dimension=\"idle\", family=\"utilization\", instance=\"192.168.1.70:19999\", job=\"noted\"}",
     "legendFormat": "__auto",
     "query": "SELECT last(\"usage_idle\") * -1 + 100 FROM \"cpu\" WHERE (\"cpu\" = 'cpu-total') AND $timeFilter GROUP BY time($interval) fill(null)"
    }
   ]
  },
  {
   "title": "RAM Usage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - netdata_cpu_cpu_percentage_average{chart=\"cpu.cpu4\", cpu=\"cpu4\", dimension=\"idle\", family=\"utilization\", instance=\"192.168.1.70:19999\", job=\"noted\"}",
     "legendFormat": "__auto",
     "query": "SELECT last(\"used_percent\") FROM \"mem\" WHERE $timeFilter GROUP BY time($interval) fill(null)"
    }
   ]
  },
  {
   "title": "Swap",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - netdata_cpu_cpu_percentage_average{chart=\"cpu.cpu4\", cpu=\"cpu4\", dimension=\"idle\", family=\"utilization\", instance=\"192.168.1.70:19999\", job=\"noted\"}",
     "legendFormat": "__auto",
     "query": "SELECT last(\"used_percent\") FROM \"swap\" WHERE $timeFilter GROUP BY time($interval) fill(null)"
    }
   ]
  },
  {
   "title": "Disk",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "disk",
     "query": "SELECT last(\"used_percent\") FROM \"disk\" WHERE (\"path\" = '/') AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" },
      { "condition": "AND", "key": "path", "operator": "=", "value": "/" }
     ]
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "netdata_system_uptime_seconds_average{chart=\"system.uptime\",dimension=\"uptime\",family=\"uptime\",instance=\"192.168.1.70:19999\",job=\"noted\"}",
     "legendFormat": "__auto",
     "query": "SELECT last(\"uptime\") FROM \"system\" WHERE $timeFilter GROUP BY time($interval) fill(null)"
    }
   ]
  },
  {
   "title": "Temp",
   "type": "stat",
   "gridPos": { "h": 4, "w": 9, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Board",
     "expr": "netdata_net_net_kilobits_persec_average{chart=\"net.eth0\",dimension=\"sent\",family=\"eth0\",instance=\"192.168.1.70:19999\",job=\"noted\"}*-1",
     "legendFormat": "Sent",
     "query": "SELECT last(\"temp\") FROM \"temp\" WHERE (\"sensor\" = 'acpitz') AND $timeFilter GROUP BY time($interval) fill(null)"
    },
    {
     "alias": "SSD",
     "query": "SELECT last(\"temp\") FROM \"temp\" WHERE (\"sensor\" = 'nvme_composite') AND $timeFilter GROUP BY time($interval) fill(null)"
    },
    {
     "alias": "CPU",
     "query": "SELECT last(\"temp\") FROM \"temp\" WHERE (\"sensor\" = 'coretemp_package_id_0') AND $timeFilter GROUP BY time($interval) fill(null)"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "query": "SELECT last(\"usage_idle\") * -1 + 100 FROM \"cpu\" WHERE (\"cpu\" = 'cpu-total') AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "usage_idle" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "* -1 + 100" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" },
      { "condition": "AND", "key": "cpu", "operator": "=", "value": "cpu-total" }
     ]
    }
   ]
  },
  {
   "title": "RAM",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mem",
     "query": "SELECT last(\"used_percent\") FROM \"mem\" WHERE $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "Swap",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "swap",
     "query": "SELECT last(\"used_percent\") FROM \"swap\" WHERE $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "Disk",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 6, "x": 9, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "decbits" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$col",
     "expr": "netdata_disk_space_GiB_average{chart=\"disk_space._\", dimension=\"avail\", family=\"/\", instance=\"192.168.1.70:19999\", job=\"noted\"}",
     "legendFormat": "Available",
     "query": "SELECT \n  last(\"total\") AS \"Total\",\n  last(\"used\") AS \"Used\",\n  last(\"free\") AS \"Free\"\nFROM \"disk\"\nWHERE $timeFilter\nGROUP BY time($interval) fill(null)"
    }
   ]
  },
  {
   "title": "Board",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "disk",
     "query": "SELECT last(\"temp\") FROM \"temp\" WHERE (\"sensor\" = 'acpitz') AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" },
      { "condition": "AND", "key": "path", "operator": "=", "value": "/" }
     ]
    }
   ]
  },
  {
   "title": "SSD",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "disk",
     "query": "SELECT last(\"temp\") FROM \"temp\" WHERE (\"sensor\" = 'nvme_composite') AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" },
      { "condition": "AND", "key": "path", "operator": "=", "value": "/" }
     ]
    }
   ]
  },
  {
   "title": "CPU",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "disk",
     "query": "SELECT last(\"temp\") FROM \"temp\" WHERE (\"sensor\" = 'coretemp_package_id_0') AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" },
      { "condition": "AND", "key": "path", "operator": "=", "value": "/" }
     ]
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "$tag_host: $col",
     "function": "mean",
     "groupBy": [
      { "interval": "auto", "params": [ "auto" ], "type": "time" },
      { "key": "host", "params": [ "tag" ], "type": "tag" }
     ],
     "measurement": "cpu_percentageBusy",
     "query": "SELECT mean(usage_user) as \"user\", mean(usage_system) as \"system\", mean(usage_softirq) as \"softirq\", mean(usage_steal) as \"steal\", mean(usage_nice) as \"nice\", mean(usage_irq) as \"irq\", mean(usage_iowait) as \"iowait\", mean(usage_guest) as \"guest\", mean(usage_guest_nice) as \"guest_nice\"  FROM \"cpu\" WHERE cpu = 'cpu-total' AND $timeFilter GROUP BY time($interval), *",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Cores",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "$tag_cpu",
     "function": "mean",
     "groupBy": [
      { "interval": "auto", "params": [ "auto" ], "type": "time" },
      { "key": "host", "params": [ "tag" ], "type": "tag" }
     ],
     "measurement": "cpu_percentageBusy",
     "query": "SELECT 100 - mean(\"usage_idle\") FROM \"cpu\" WHERE (\"cpu\" =~ /cpu[0-9].*/) AND $timeFilter GROUP BY time($interval), \"cpu\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "RAM",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "alias": "$tag_host: $col",
     "function": "mean",
     "groupBy": [
      { "interval": "auto", "params": [ "auto" ], "type": "time" },
      { "key": "host", "params": [ "tag" ], "type": "tag" }
     ],
     "measurement": "mem_inactive",
     "query": "SELECT mean(total) as total, mean(used) as used  FROM \"mem\" WHERE $timeFilter GROUP BY time($interval), host ORDER BY asc",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}