# Bu araç @keyiflerolsun tarafından | @KekikAkademi için yazılmıştır.

version: "3.9"

networks:
    local:
        driver: bridge

services:

    telegraf:
        container_name : telegraf
        image          : telegraf:latest
        restart        : always

        networks:
            - local
        volumes:
            - ./telegraf.conf:/etc/telegraf/telegraf.conf
            - /var/run/docker.sock:/var/run/docker.sock
